2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Configure stats pid to 10216
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Loading settings from C:\Users\janfr\.config\wandb\settings
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Loading settings from c:\Users\janfr\Documents\python_projects\masterarbeit\wandb\settings
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_init.py:_log_setup():521] Logging user logs to c:\Users\janfr\Documents\python_projects\masterarbeit\wandb\run-20240407_173511-jy43ogox\logs\debug.log
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_init.py:_log_setup():522] Logging internal logs to c:\Users\janfr\Documents\python_projects\masterarbeit\wandb\run-20240407_173511-jy43ogox\logs\debug-internal.log
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000177067F0820>
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_init.py:init():561] calling init triggers
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'dataset': 'Coca Cola closing prices', 'architecture': 'GRU ', 'num_units': 40, 'num_layers': 1, 'dropout': 0, 'seq_length': 13, 'start_date': '1990-01-01', 'end_date': '2024-01-01', 'epochs': 200, 'learning_rate': 0.001}
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_init.py:init():611] starting backend
2024-04-07 17:35:11,873 INFO    MainThread:10216 [wandb_init.py:init():615] setting up manager
2024-04-07 17:35:11,881 INFO    MainThread:10216 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-07 17:35:11,882 INFO    MainThread:10216 [wandb_init.py:init():623] backend started and connected
2024-04-07 17:35:11,888 INFO    MainThread:10216 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-07 17:35:11,888 INFO    MainThread:10216 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-07 17:35:11,888 INFO    MainThread:10216 [wandb_init.py:init():715] updated telemetry
2024-04-07 17:35:11,889 INFO    MainThread:10216 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-07 17:35:12,425 INFO    MainThread:10216 [wandb_run.py:_on_init():2357] communicating current version
2024-04-07 17:35:12,734 INFO    MainThread:10216 [wandb_run.py:_on_init():2366] got version response 
2024-04-07 17:35:12,734 INFO    MainThread:10216 [wandb_init.py:init():799] starting run threads in backend
2024-04-07 17:35:16,742 INFO    MainThread:10216 [wandb_run.py:_console_start():2335] atexit reg
2024-04-07 17:35:16,742 INFO    MainThread:10216 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-07 17:35:16,742 INFO    MainThread:10216 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-07 17:35:16,744 INFO    MainThread:10216 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-07 17:35:16,744 INFO    MainThread:10216 [wandb_init.py:init():842] run started, returning control to user process
2024-04-07 17:36:12,594 ERROR   MainThread:10216 [util.py:get_module():270] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "c:\Users\janfr\anaconda3\envs\pytorch_3_10\lib\site-packages\wandb\util.py", line 236, in import_module_lazy
    return sys.modules[name]
KeyError: 'plotly.tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\janfr\anaconda3\envs\pytorch_3_10\lib\site-packages\wandb\util.py", line 265, in get_module
    return import_module_lazy(name)
  File "c:\Users\janfr\anaconda3\envs\pytorch_3_10\lib\site-packages\wandb\util.py", line 238, in import_module_lazy
    spec = importlib.util.find_spec(name)
  File "c:\Users\janfr\anaconda3\envs\pytorch_3_10\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'plotly'
2024-04-07 17:36:14,575 INFO    MainThread:10216 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 17:36:14,575 INFO    MainThread:10216 [wandb_init.py:_pause_backend():432] pausing backend
