
Epoch 0: 100%|██████████| 48/48 [00:00<00:00, 82.60it/s, v_num=i6et, train_loss_step=0.0403, val_loss_step=0.424, val_loss_epoch=0.232, train_loss_epoch=0.151]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
  | Name      | Type     | Params
---------------------------------------
0 | model     | RNNModel | 1.8 K
1 | criterion | MSELoss  | 0
---------------------------------------
1.8 K     Trainable params
0         Non-trainable params
1.8 K     Total params
0.007     Total estimated model params size (MB)
c:\Users\janfr\anaconda3\envs\pytorch_3_10\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:441: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.
c:\Users\janfr\anaconda3\envs\pytorch_3_10\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=15` in the `DataLoader` to improve performance.


























Epoch 29: 100%|██████████| 48/48 [00:00<00:00, 61.09it/s, v_num=i6et, train_loss_step=0.00649, val_loss_step=0.00811, val_loss_epoch=0.00313, train_loss_epoch=0.00136]
Testing DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 232.57it/s]
`Trainer.fit` stopped: `max_epochs=30` reached.
Restoring states from the checkpoint path at .\RNN_single_step_forecasts\7kpei6et\checkpoints\epoch=29-step=1440.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Loaded model weights from the checkpoint at .\RNN_single_step_forecasts\7kpei6et\checkpoints\epoch=29-step=1440.ckpt
